import datetime
from utils.audit_logger import log_action

def generate_runbook(pod_name: str, namespace: str, issue: str, resolution: str) -> dict:
    timestamp = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    runbook_id = f"RB-{datetime.datetime.utcnow().strftime('%Y%m%d%H%M%S')}"

    runbook = f"""
# Incident Runbook -- {runbook_id}

## Incident Details
- **Date:** {timestamp}
- **Pod:** {pod_name}
- **Namespace:** {namespace}
- **Runbook ID:** {runbook_id}

## Issue Summary
{issue}

## Diagnosis Steps Taken
1. Checked pod status using kubectl get pods
2. Described pod to review events and container states
3. Analysed container logs for error patterns
4. Reviewed namespace events for cluster-level issues

## Resolution
{resolution}

## Prevention Recommendations
1. Set appropriate resource requests and limits on all containers
2. Configure liveness and readiness probes for all deployments
3. Set up alerting for CrashLoopBackOff and OOMKilled events
4. Review application startup dependencies and add retry logic
5. Enable pod disruption budgets for critical workloads

## Compliance Notes
- All diagnostic commands have been logged in the audit trail
- No data was modified without explicit tool calls
- This runbook should be stored in your incident management system

## Generated By
k8s-ai-agent -- AI-powered Kubernetes diagnostics
github.com/santosh7676/k8s-ai-agent
"""

    filename = f"runbook_{runbook_id}.md"
    with open(filename, "w") as f:
        f.write(runbook)

    log_action("RUNBOOK_GENERATED", f"{pod_name}/{namespace}", filename)
    return {"success": True, "output": f"Runbook generated and saved as {filename}\n\n{runbook}"}
